export const Seasonal = [
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/1/",
    district: "Kibaale",
    dec_jan_feb: 135.69,
    mar_apr_may: 361.95,
    jun_jul_aug: 231.66,
    sep_oct_nov: 455.34,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/2/",
    district: "Kasese",
    dec_jan_feb: 196.37,
    mar_apr_may: 326.96,
    jun_jul_aug: 204.42,
    sep_oct_nov: 402.93,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/3/",
    district: "Tororo",
    dec_jan_feb: 222.77,
    mar_apr_may: 554.37,
    jun_jul_aug: 355.24,
    sep_oct_nov: 465.55,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/4/",
    district: "Bukomansimbi",
    dec_jan_feb: 251.84,
    mar_apr_may: 541.29,
    jun_jul_aug: 178.39,
    sep_oct_nov: 404.56,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/5/",
    district: "Kalangala",
    dec_jan_feb: 289.2,
    mar_apr_may: 512.84,
    jun_jul_aug: 200.26,
    sep_oct_nov: 422.87,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/6/",
    district: "Bukwo",
    dec_jan_feb: 109.76,
    mar_apr_may: 369.03,
    jun_jul_aug: 464.13,
    sep_oct_nov: 323.87,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/7/",
    district: "Bulambuli",
    dec_jan_feb: 125.96,
    mar_apr_may: 419.23,
    jun_jul_aug: 391.07,
    sep_oct_nov: 352.83,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/8/",
    district: "Kabale",
    dec_jan_feb: 274.12,
    mar_apr_may: 353.32,
    jun_jul_aug: 131.7,
    sep_oct_nov: 379.81,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/9/",
    district: "Buliisa",
    dec_jan_feb: 90.47,
    mar_apr_may: 327.53,
    jun_jul_aug: 333.31,
    sep_oct_nov: 438.36,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/10/",
    district: "Jinja",
    dec_jan_feb: 251.44,
    mar_apr_may: 518.49,
    jun_jul_aug: 266.24,
    sep_oct_nov: 481.86,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/11/",
    district: "Arua",
    dec_jan_feb: 69.3,
    mar_apr_may: 301.8,
    jun_jul_aug: 433.26,
    sep_oct_nov: 452.91,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/12/",
    district: "Bundibugyo",
    dec_jan_feb: 177.95,
    mar_apr_may: 355.18,
    jun_jul_aug: 243.85,
    sep_oct_nov: 437.78,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/13/",
    district: "Bushenyi",
    dec_jan_feb: 212.24,
    mar_apr_may: 318.66,
    jun_jul_aug: 161.96,
    sep_oct_nov: 397.76,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/14/",
    district: "Buyende",
    dec_jan_feb: 172.37,
    mar_apr_may: 488.04,
    jun_jul_aug: 329.49,
    sep_oct_nov: 486.38,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/15/",
    district: "Butambala",
    dec_jan_feb: 238.47,
    mar_apr_may: 496.84,
    jun_jul_aug: 219.02,
    sep_oct_nov: 425.54,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/16/",
    district: "Iganga",
    dec_jan_feb: 233.92,
    mar_apr_may: 517.08,
    jun_jul_aug: 286.17,
    sep_oct_nov: 468.58,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/17/",
    district: "Kalungu",
    dec_jan_feb: 247.97,
    mar_apr_may: 532.86,
    jun_jul_aug: 179.7,
    sep_oct_nov: 406.23,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/18/",
    district: "Rukungiri",
    dec_jan_feb: 213.71,
    mar_apr_may: 290.37,
    jun_jul_aug: 170.79,
    sep_oct_nov: 347.89,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/19/",
    district: "Kamuli",
    dec_jan_feb: 213.83,
    mar_apr_may: 500.39,
    jun_jul_aug: 291.92,
    sep_oct_nov: 489.68,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/20/",
    district: "Kapchorwa",
    dec_jan_feb: 132.38,
    mar_apr_may: 429.8,
    jun_jul_aug: 395.34,
    sep_oct_nov: 356.92,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/21/",
    district: "Koboko",
    dec_jan_feb: 61.19,
    mar_apr_may: 318.39,
    jun_jul_aug: 481.08,
    sep_oct_nov: 446.45,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/22/",
    district: "Sheema",
    dec_jan_feb: 214.03,
    mar_apr_may: 304.85,
    jun_jul_aug: 144.6,
    sep_oct_nov: 385.28,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/23/",
    district: "Kitgum",
    dec_jan_feb: 58.39,
    mar_apr_may: 315.47,
    jun_jul_aug: 454.63,
    sep_oct_nov: 287.9,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/24/",
    district: "Kole",
    dec_jan_feb: 105.72,
    mar_apr_may: 423.7,
    jun_jul_aug: 440.72,
    sep_oct_nov: 466.92,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/25/",
    district: "Kyankwanzi",
    dec_jan_feb: 145.54,
    mar_apr_may: 393.15,
    jun_jul_aug: 257.08,
    sep_oct_nov: 475.56,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/26/",
    district: "Kisoro",
    dec_jan_feb: 313.13,
    mar_apr_may: 390.01,
    jun_jul_aug: 154.02,
    sep_oct_nov: 410.25,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/27/",
    district: "Kotido",
    dec_jan_feb: 57.96,
    mar_apr_may: 264.11,
    jun_jul_aug: 369.51,
    sep_oct_nov: 208.94,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/28/",
    district: "Kween",
    dec_jan_feb: 106.08,
    mar_apr_may: 365.88,
    jun_jul_aug: 432.54,
    sep_oct_nov: 315.97,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/29/",
    district: "Nakaseke",
    dec_jan_feb: 160.5,
    mar_apr_may: 415.1,
    jun_jul_aug: 255.36,
    sep_oct_nov: 475.6,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/30/",
    district: "Lamwo",
    dec_jan_feb: 56.91,
    mar_apr_may: 324.39,
    jun_jul_aug: 479.23,
    sep_oct_nov: 334.05,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/31/",
    district: "Luuka",
    dec_jan_feb: 230.76,
    mar_apr_may: 507.48,
    jun_jul_aug: 281.48,
    sep_oct_nov: 489.99,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/32/",
    district: "Mityana",
    dec_jan_feb: 215.9,
    mar_apr_may: 463.24,
    jun_jul_aug: 221.23,
    sep_oct_nov: 436.04,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/33/",
    district: "Manafwa",
    dec_jan_feb: 217.01,
    mar_apr_may: 561.09,
    jun_jul_aug: 375.26,
    sep_oct_nov: 464.88,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/34/",
    district: "Nakasongola",
    dec_jan_feb: 147.24,
    mar_apr_may: 441.36,
    jun_jul_aug: 295.25,
    sep_oct_nov: 492.9,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/35/",
    district: "Mubende",
    dec_jan_feb: 175.4,
    mar_apr_may: 395.58,
    jun_jul_aug: 198.81,
    sep_oct_nov: 437.64,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/36/",
    district: "Mbale",
    dec_jan_feb: 166.17,
    mar_apr_may: 483.24,
    jun_jul_aug: 384.79,
    sep_oct_nov: 400.19,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/37/",
    district: "Mbarara",
    dec_jan_feb: 221.64,
    mar_apr_may: 326.31,
    jun_jul_aug: 139.48,
    sep_oct_nov: 400.94,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/38/",
    district: "Luwero",
    dec_jan_feb: 203.71,
    mar_apr_may: 461.58,
    jun_jul_aug: 252.51,
    sep_oct_nov: 487.2,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/39/",
    district: "Mayuge",
    dec_jan_feb: 279.68,
    mar_apr_may: 533.34,
    jun_jul_aug: 244.92,
    sep_oct_nov: 423.73,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/40/",
    district: "Bududa",
    dec_jan_feb: 138.72,
    mar_apr_may: 439.43,
    jun_jul_aug: 394.34,
    sep_oct_nov: 364.97,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/41/",
    district: "Kayunga",
    dec_jan_feb: 196.01,
    mar_apr_may: 480.48,
    jun_jul_aug: 271.63,
    sep_oct_nov: 495.97,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/42/",
    district: "Ssembabule",
    dec_jan_feb: 208.5,
    mar_apr_may: 419.48,
    jun_jul_aug: 172.06,
    sep_oct_nov: 420.6,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/43/",
    district: "Mpigi",
    dec_jan_feb: 255.01,
    mar_apr_may: 512.58,
    jun_jul_aug: 216.54,
    sep_oct_nov: 424.88,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/44/",
    district: "Kyenjojo",
    dec_jan_feb: 148.74,
    mar_apr_may: 361.94,
    jun_jul_aug: 219.89,
    sep_oct_nov: 460.49,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/45/",
    district: "Kiryandongo",
    dec_jan_feb: 103.48,
    mar_apr_may: 386.96,
    jun_jul_aug: 374.1,
    sep_oct_nov: 465.4,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/46/",
    district: "Kyegegwa",
    dec_jan_feb: 162.83,
    mar_apr_may: 365.74,
    jun_jul_aug: 196.55,
    sep_oct_nov: 440.3,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/47/",
    district: "Gomba",
    dec_jan_feb: 208.84,
    mar_apr_may: 444.79,
    jun_jul_aug: 194.94,
    sep_oct_nov: 423.89,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/48/",
    district: "Mitooma",
    dec_jan_feb: 214.42,
    mar_apr_may: 295.19,
    jun_jul_aug: 153.36,
    sep_oct_nov: 366.59,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/49/",
    district: "Ntungamo",
    dec_jan_feb: 216.89,
    mar_apr_may: 299.78,
    jun_jul_aug: 124.73,
    sep_oct_nov: 365.31,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/50/",
    district: "Buvuma",
    dec_jan_feb: 291.98,
    mar_apr_may: 530.14,
    jun_jul_aug: 238.73,
    sep_oct_nov: 424.59,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/51/",
    district: "Masaka",
    dec_jan_feb: 316.86,
    mar_apr_may: 612.1,
    jun_jul_aug: 187.63,
    sep_oct_nov: 420.71,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/52/",
    district: "Butaleja",
    dec_jan_feb: 222.63,
    mar_apr_may: 527.1,
    jun_jul_aug: 322.3,
    sep_oct_nov: 453.78,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/53/",
    district: "Masindi",
    dec_jan_feb: 120.41,
    mar_apr_may: 391.76,
    jun_jul_aug: 331.35,
    sep_oct_nov: 472.31,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/54/",
    district: "Moroto",
    dec_jan_feb: 60.87,
    mar_apr_may: 260.7,
    jun_jul_aug: 319.21,
    sep_oct_nov: 179.15,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/55/",
    district: "Nakapiripirit",
    dec_jan_feb: 86.68,
    mar_apr_may: 333.04,
    jun_jul_aug: 366.38,
    sep_oct_nov: 275.07,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/56/",
    district: "Namutumba",
    dec_jan_feb: 225.79,
    mar_apr_may: 518.75,
    jun_jul_aug: 306.6,
    sep_oct_nov: 453.74,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/57/",
    district: "Kibuku",
    dec_jan_feb: 187.21,
    mar_apr_may: 493.64,
    jun_jul_aug: 362.13,
    sep_oct_nov: 430.56,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/58/",
    district: "Napak",
    dec_jan_feb: 73.49,
    mar_apr_may: 307.39,
    jun_jul_aug: 368.82,
    sep_oct_nov: 266.4,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/59/",
    district: "Kiboga",
    dec_jan_feb: 168.77,
    mar_apr_may: 397.15,
    jun_jul_aug: 223.62,
    sep_oct_nov: 455.05,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/60/",
    district: "Moyo",
    dec_jan_feb: 45.69,
    mar_apr_may: 276.03,
    jun_jul_aug: 414.49,
    sep_oct_nov: 373.51,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/61/",
    district: "Nebbi",
    dec_jan_feb: 68.13,
    mar_apr_may: 287.03,
    jun_jul_aug: 375.73,
    sep_oct_nov: 429.39,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/62/",
    district: "Ngora",
    dec_jan_feb: 147.03,
    mar_apr_may: 461.62,
    jun_jul_aug: 397.17,
    sep_oct_nov: 422.23,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/63/",
    district: "Kaberamaido",
    dec_jan_feb: 131.01,
    mar_apr_may: 446.38,
    jun_jul_aug: 391.94,
    sep_oct_nov: 459.59,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/64/",
    district: "Katakwi",
    dec_jan_feb: 98.53,
    mar_apr_may: 377.99,
    jun_jul_aug: 392.39,
    sep_oct_nov: 351.46,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/65/",
    district: "Buhweju",
    dec_jan_feb: 214.72,
    mar_apr_may: 340.91,
    jun_jul_aug: 178.3,
    sep_oct_nov: 422.86,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/66/",
    district: "Kampala",
    dec_jan_feb: 279.29,
    mar_apr_may: 523.66,
    jun_jul_aug: 229.98,
    sep_oct_nov: 438.85,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/67/",
    district: "Kiruhura",
    dec_jan_feb: 213.06,
    mar_apr_may: 371.08,
    jun_jul_aug: 162.07,
    sep_oct_nov: 426.36,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/68/",
    district: "Ntoroko",
    dec_jan_feb: 155.32,
    mar_apr_may: 347.1,
    jun_jul_aug: 258.71,
    sep_oct_nov: 434.91,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/69/",
    district: "Kamwenge",
    dec_jan_feb: 174.21,
    mar_apr_may: 335.32,
    jun_jul_aug: 185.8,
    sep_oct_nov: 416.27,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/70/",
    district: "Kanungu",
    dec_jan_feb: 228.19,
    mar_apr_may: 301.04,
    jun_jul_aug: 172.85,
    sep_oct_nov: 353.95,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/71/",
    district: "Kaabong",
    dec_jan_feb: 55.89,
    mar_apr_may: 244.76,
    jun_jul_aug: 368.5,
    sep_oct_nov: 188.51,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/72/",
    district: "Kaliro",
    dec_jan_feb: 191.45,
    mar_apr_may: 496.36,
    jun_jul_aug: 337.74,
    sep_oct_nov: 464.26,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/73/",
    district: "Ibanda",
    dec_jan_feb: 200.77,
    mar_apr_may: 346.91,
    jun_jul_aug: 175.53,
    sep_oct_nov: 425.97,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/74/",
    district: "Kabarole",
    dec_jan_feb: 166.17,
    mar_apr_may: 346.16,
    jun_jul_aug: 223.1,
    sep_oct_nov: 431.9,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/75/",
    district: "Isingiro",
    dec_jan_feb: 252.95,
    mar_apr_may: 368.83,
    jun_jul_aug: 129.61,
    sep_oct_nov: 391.08,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/76/",
    district: "Lyantonde",
    dec_jan_feb: 228.3,
    mar_apr_may: 422.74,
    jun_jul_aug: 160.45,
    sep_oct_nov: 420.19,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/77/",
    district: "Rakai",
    dec_jan_feb: 343.16,
    mar_apr_may: 589.38,
    jun_jul_aug: 175.8,
    sep_oct_nov: 426.84,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/78/",
    district: "Lira",
    dec_jan_feb: 100.29,
    mar_apr_may: 415.47,
    jun_jul_aug: 447.36,
    sep_oct_nov: 446.03,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/79/",
    district: "Maracha",
    dec_jan_feb: 78.82,
    mar_apr_may: 332.73,
    jun_jul_aug: 490.59,
    sep_oct_nov: 495.71,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/80/",
    district: "Otuke",
    dec_jan_feb: 91.59,
    mar_apr_may: 379.86,
    jun_jul_aug: 436.56,
    sep_oct_nov: 385.92,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/81/",
    district: "Oyam",
    dec_jan_feb: 95.31,
    mar_apr_may: 409.92,
    jun_jul_aug: 441.9,
    sep_oct_nov: 460.34,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/82/",
    district: "Pader",
    dec_jan_feb: 73.03,
    mar_apr_may: 389.34,
    jun_jul_aug: 491.34,
    sep_oct_nov: 391.9,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/83/",
    district: "Pallisa",
    dec_jan_feb: 173.52,
    mar_apr_may: 482.6,
    jun_jul_aug: 374.98,
    sep_oct_nov: 422.03,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/84/",
    district: "Rubirizi",
    dec_jan_feb: 197.77,
    mar_apr_may: 308.06,
    jun_jul_aug: 182.07,
    sep_oct_nov: 373.36,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/85/",
    district: "Namayingo",
    dec_jan_feb: 275.66,
    mar_apr_may: 528.87,
    jun_jul_aug: 254.6,
    sep_oct_nov: 417.46,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/86/",
    district: "Sironko",
    dec_jan_feb: 133.62,
    mar_apr_may: 433.13,
    jun_jul_aug: 391.57,
    sep_oct_nov: 358.73,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/87/",
    district: "Mukono",
    dec_jan_feb: 263.94,
    mar_apr_may: 510.31,
    jun_jul_aug: 235.71,
    sep_oct_nov: 450.86,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/88/",
    district: "Soroti",
    dec_jan_feb: 119.04,
    mar_apr_may: 437.55,
    jun_jul_aug: 413.48,
    sep_oct_nov: 427.63,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/89/",
    district: "Lwengo",
    dec_jan_feb: 244.05,
    mar_apr_may: 466.33,
    jun_jul_aug: 164.36,
    sep_oct_nov: 414.65,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/90/",
    district: "Zombo",
    dec_jan_feb: 113.11,
    mar_apr_may: 358.2,
    jun_jul_aug: 429.64,
    sep_oct_nov: 520.49,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/91/",
    district: "Serere",
    dec_jan_feb: 154.54,
    mar_apr_may: 469.94,
    jun_jul_aug: 373.19,
    sep_oct_nov: 459.19,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/92/",
    district: "Bukedea",
    dec_jan_feb: 132.43,
    mar_apr_may: 430.04,
    jun_jul_aug: 388.14,
    sep_oct_nov: 360.24,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/93/",
    district: "Gulu",
    dec_jan_feb: 71.95,
    mar_apr_may: 394.7,
    jun_jul_aug: 491.11,
    sep_oct_nov: 441.47,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/94/",
    district: "Nwoya",
    dec_jan_feb: 73.42,
    mar_apr_may: 347.95,
    jun_jul_aug: 419.39,
    sep_oct_nov: 444.92,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/95/",
    district: "Amolatar",
    dec_jan_feb: 130.03,
    mar_apr_may: 435.1,
    jun_jul_aug: 355.67,
    sep_oct_nov: 477.56,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/96/",
    district: "Dokolo",
    dec_jan_feb: 121.97,
    mar_apr_may: 433.51,
    jun_jul_aug: 401.81,
    sep_oct_nov: 454.35,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/97/",
    district: "Amuria",
    dec_jan_feb: 100.98,
    mar_apr_may: 387.3,
    jun_jul_aug: 412.82,
    sep_oct_nov: 389.01,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/98/",
    district: "Wakiso",
    dec_jan_feb: 255.84,
    mar_apr_may: 506.85,
    jun_jul_aug: 227.65,
    sep_oct_nov: 435.97,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/99/",
    district: "Yumbe",
    dec_jan_feb: 51.34,
    mar_apr_may: 293.4,
    jun_jul_aug: 450.7,
    sep_oct_nov: 413.97,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/100/",
    district: "Kumi",
    dec_jan_feb: 143.64,
    mar_apr_may: 446.15,
    jun_jul_aug: 384.94,
    sep_oct_nov: 398.05,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/101/",
    district: "Agago",
    dec_jan_feb: 73.05,
    mar_apr_may: 346.92,
    jun_jul_aug: 450.58,
    sep_oct_nov: 332.48,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/102/",
    district: "Alebtong",
    dec_jan_feb: 102.76,
    mar_apr_may: 404.8,
    jun_jul_aug: 431.92,
    sep_oct_nov: 423.92,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/103/",
    district: "Hoima",
    dec_jan_feb: 113.38,
    mar_apr_may: 349.4,
    jun_jul_aug: 277.34,
    sep_oct_nov: 449.54,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/104/",
    district: "Busia",
    dec_jan_feb: 237.76,
    mar_apr_may: 540.09,
    jun_jul_aug: 267.77,
    sep_oct_nov: 436.6,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/105/",
    district: "Adjumani",
    dec_jan_feb: 51.29,
    mar_apr_may: 295.16,
    jun_jul_aug: 420.02,
    sep_oct_nov: 397.64,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/106/",
    district: "Abim",
    dec_jan_feb: 68.51,
    mar_apr_may: 304.75,
    jun_jul_aug: 396.76,
    sep_oct_nov: 271.1,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/107/",
    district: "Amudat",
    dec_jan_feb: 84.38,
    mar_apr_may: 320.01,
    jun_jul_aug: 370.67,
    sep_oct_nov: 256.45,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/108/",
    district: "Amuru",
    dec_jan_feb: 61.06,
    mar_apr_may: 337.48,
    jun_jul_aug: 451.13,
    sep_oct_nov: 416.64,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/109/",
    district: "Apac",
    dec_jan_feb: 121.62,
    mar_apr_may: 425.09,
    jun_jul_aug: 377.07,
    sep_oct_nov: 477.15,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/110/",
    district: "Budaka",
    dec_jan_feb: 171.32,
    mar_apr_may: 473.91,
    jun_jul_aug: 366.89,
    sep_oct_nov: 406.01,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/111/",
    district: "Bugiri",
    dec_jan_feb: 239.94,
    mar_apr_may: 523.46,
    jun_jul_aug: 262.99,
    sep_oct_nov: 438.0,
  },
  {
    url: "https://smart-crop-calendar.herokuapp.com/crops/seasonal_precipitation/112/",
    district: "Buikwe",
    dec_jan_feb: 301.46,
    mar_apr_may: 544.64,
    jun_jul_aug: 228.31,
    sep_oct_nov: 443.33,
  },
];
